prefix owl: <http://www.w3.org/2002/07/owl#>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix dce: <http://purl.org/dc/elements/1.1/>
prefix dcat: <http://www.w3.org/ns/dcat#>

SELECT ?ont ?name WHERE 
{
  ?ont dcat:contactPoint ?person .
  ?person rdfs:label ?name

}
