name: Run and Apply Linter
on:
  workflow_dispatch:
  pull_request:
    branches: [ master ]
jobs:
  run-and-apply:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Install dependencies
        run: |
          pip install --upgrade pip setuptools wheel
          pip install "tox<4.0.0"
      - name: Permission workaround
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"
      - name: Run linter
        run: tox -e lint
      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          message: 'Commit automated linter changes'
          add: '.'
