# Workflow for MRO Testing

name: OBOFoundry Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    if: github.triggering_actor != 'github-actions[bot]'
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@master
        with:
          python-version: '3.9'
      - name: Install requirements
        run: |
          python3 -m pip install -r requirements.txt
      - name: Run tests
        run: |
          make test
